project:
  type: website

website:
  title: "IS415: Geospatial Analytics & Applications"
  navbar:
    left:
    - text: "Hands-on Exercise"
      menu:
        - text: "Hands-on Exercise 1: Geospatial Data Wrangling"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
        - text: "Hands-on Exercise 2: Choropleth Mapping"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
        - text: "Hands-on Exercise 3: 1st Order Spatial Point Patterns"
          href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html"
        - text: "Hands-on Exercise 6: Spatial Weights"
          href: "Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.html"
        - text: "Hands-on Exercise 7: GLSA"
          href: "Hands-on_Ex/Hands-on_Ex07_GLSA/Hands-on_Ex07_GLSA.html"
        - text: "Hands-on Exercise 7: EHSA"
          href: "Hands-on_Ex/Hands-on_Ex07_EHSA/Hands-on_Ex07_EHSA.html"
        - text: "Hands-on Exercise 8: Hedonic Pricing Model (GWR)"
          href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08.html"
        - text: "Hands-on Exercise 9: Geographical Segmentation"
          href: "Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex09.html"
        - text: "Hands-on Exercise 10: Spatial Interaction Models"
          href: "Hands-on_Ex/Hands-on_Ex10/Hands-on_Ex10.html"
        - text: "Hands-on Exercise 11: Geographical Accessibility"
          href: "Hands-on_Ex/Hands-on_Ex11/Hands-on_Ex11.html"
    - text: "In-class Exercise"
      menu: 
        - text: "In-class Exercise 2: Geospatial Data Wrangling"
          href: "In-class_Ex/In-class_Ex02/In-class_Ex02.html"
        - text: "In-class Exercise 3: Choropleth Mapping"
          href: "In-class_Ex/In-class_Ex03/In-class_Ex03.html"
        - text: "In-class Exercise 4: 2nd Order Spatial Point Patterns"
          href: "In-class_Ex/In-class_Ex04/In-class_Ex04.html"
        - text: "In-class Exercise 5: Local Colocation Quotient"
          href: "In-class_Ex/In-class_Ex05/In-class_Ex05.html"
        - text: "In-class Exercise 6: Spatial Weights (sfdep)"
          href: "In-class_Ex/In-class_Ex06/In-class_Ex06.html"
        - text: "In-class Exercise 7: EHSA (sfdep)"
          href: "In-class_Ex/In-class_Ex07/In-class_Ex07.html"
        - text: "In-class Exercise 8: Hedonic Pricing Model (GWR)"
          href: "In-class_Ex/In-class_Ex08/In-class_Ex08.html"
        - text: "In-class Exercise 9: Geographical Segmentation"
          href: "In-class_Ex/In-class_Ex09/In-class_Ex09.html"
        - text: "In-class Exercise 10: Spatial Interaction Models"
          href: "In-class_Ex/In-class_Ex10/In-class_Ex10.html"
        - text: "In-class Exercise 11: Geographical Accessibility"
          href: "In-class_Ex/In-class_Ex11/In-class_Ex11.html"
    - text: "Take-home Exercise"
      menu: 
        - text: "Take-home Exercise 1"
          href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html"
        - text: "Take-home Exercise 2"
          href: "Take-home_Ex/Take-home_Ex02/Take-home_Ex02.html"
        - text: "Take-home Exercise 3"
          href: "Take-home_Ex/Take-home_Ex03/Take-home_Ex03.html"
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: Journal
    css: styles.css
    toc: true
    number-sections: true
    highlight-style: tango

editor: visual

